version: "3.9"
services:
  #
  # MAVProxy (this image)
  #   Startup options: https://ardupilot.org/mavproxy/docs/getting_started/starting.html
  #
  mavproxy:
    image: sitin/mavproxy:local
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVPROXY_TAG
    stdin_open: true
    tty: true
    command:
      - --master=udp:0.0.0.0:14540              # SITL will connect here
      - --out=udp:host.docker.internal:14550    # For GCS
      - --out=udp:host.docker.internal:14540    # Extra port (usually for API)
      # The following requires DISPLAY to set properly in `.env` file
      # (also you should allow remote connections to your X-server):
      - --map             # Show map
      - --console         # Show console
    environment:
      - DISPLAY
      - SILENT_START
    volumes:
      - ./.volumes/logs:/var/log/mavproxy
      - ./.volumes/state:/mavproxy
    env_file:
      - .env
    depends_on:
      - sitl
    networks:
      default:
        ipv4_address: 10.20.2.0
  #
  # SITL simulator
  #   See details: https://hub.docker.com/r/jonasvautherin/px4-gazebo-headless
  #
  sitl:
    image: jonasvautherin/px4-gazebo-headless:latest
    command:
      - -v
      - typhoon_h480
      - 10.20.2.0     # API IP
      - 10.20.2.0     # GCS IP (not used but has to be specified)
    environment:
      - NO_PXH=1

#------------------------------------------------------------------------------
# Since px4-gazebo-headless can't use hostnames, we need to set IP for proxy
#------------------------------------------------------------------------------
networks:
  default:
    ipam:
      config:
        - subnet: 10.20.0.0/20